config/routes.rb
Rails.application.routes.draw do

  # Rutas para polideportivos (incluye index, new, create)
  resources :polideportivos, only: [:index, :new, :create]

  # Rutas para canchas (solo index, new, create)
  resources :canchas, only: [:index, :new , :create]

  # Rutas para clientes (solo new y create)
  resources :clientes, only: [:new, :create]

  # Rutas para reservas (solo new y create)

  resources :polideportivos do
    resources :canchas
  end

  resources :polideportivos do
    resources :canchas do
      resources :reservas, only: [:index, :new, :create]
    end
  end

  resources :polideportivos, only: [:index, :show, :edit, :update]


  # Define la ruta raíz de la aplicación
  root 'polideportivos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cancha.rb
class Cancha < ApplicationRecord
  belongs_to :polideportivo
  enum tipo: { "Techada" => 0, "Al aire libre" => 1 }
  has_many :reservas, dependent: :destroy # para que la cancha pueda tener muchas reserva

  has_one_attached :imagen
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/polideportivo.rb
class Polideportivo < ApplicationRecord

    has_one_attached :imagen
    has_many :canchas, dependent: :destroy
end

app/models/reserva.rb
class Reserva < ApplicationRecord
  belongs_to :cliente
  belongs_to :cancha


  #Esto permite que el formulario reservas acepte a los clientes
  accepts_nested_attributes_for :cliente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end 

app/controllers/canchas_controller.rb
class CanchasController < ApplicationController
  before_action :set_polideportivo, only: [:index, :new, :create]

  def index
    @canchas = @polideportivo.canchas
  end

  def new
    @cancha = @polideportivo.canchas.new
  end

  def create
    @cancha = @polideportivo.canchas.new(cancha_params)
    if @cancha.save
      redirect_to polideportivo_canchas_path(@polideportivo), notice: 'Cancha creada exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_polideportivo
    @polideportivo = Polideportivo.find_by(id: params[:polideportivo_id])
    redirect_to polideportivos_path, alert: "Polideportivo no encontrado" if @polideportivo.nil?
  end

  def cancha_params
    params.require(:cancha).permit(:nombre, :descripcion, :precio_dia, :precio_noche, :tipo, :imagen)
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)
    if @cliente.save
      redirect_to root_path, notice: 'Cliente registrado exitosamente.'
    else
      render :new
    end
  end

  private

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :email)
  end
  
end

app/controllers/polideportivos_controller.rb
class PolideportivosController < ApplicationController
  before_action :set_polideportivo, only: [:show, :edit, :update]

  def index
    @polideportivos = Polideportivo.all
    @polideportivo = params
  end
  def new
    @polideportivo = Polideportivo.new
  end

  def create
    @polideportivo = Polideportivo.new(polideportivo_params)

    if @polideportivo.save
      redirect_to polideportivos_path, notice: 'El polideportivo fue creado exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @polideportivo.update(polideportivo_params)
      redirect_to polideportivo_path(@polideportivo), notice: 'Polideportivo actualizado exitosamente.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_polideportivo
    @polideportivo = Polideportivo.find(params[:id])
  end

  def polideportivo_params
    params.require(:polideportivo).permit(:contacto, :ubicacion_api, :ubicacion, :nombre)
  end


  private

  def polideportivo_params
    params.require(:polideportivo).permit(:nombre, :ubicacion, :categoria, :descripcion, :contacto, :ubicacion_api, :imagen)
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_polideportivo
  before_action :set_cancha

  def index
    @reservas = @cancha.reservas
  end

  def new
    @reserva = Reserva.new
    @reserva.build_cliente # Inicializa un cliente asociado a la reserva
  end

  def create
    @reserva = @cancha.reservas.new(reserva_params)
    if @reserva.save
      redirect_to polideportivo_canchas_path(@polideportivo), notice: 'Reserva y cliente creados exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_polideportivo
    @polideportivo = Polideportivo.find_by(id: params[:polideportivo_id])
    if @polideportivo.nil?
      redirect_to polideportivos_path, alert: "Polideportivo no encontrado."
    end
  end

  def set_cancha
    @cancha = Cancha.find_by(id: params[:cancha_id])
    if @cancha.nil?
      redirect_to polideportivo_canchas_path(@polideportivo), alert: "Cancha no encontrada."
    end
  end

  def reserva_params
    params.require(:reserva).permit(:fecha, :hora_inicio, :hora_fin, cliente_attributes: [:nombre, :telefono, :email])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canchas_helper.rb
module CanchasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/polideportivos_helper.rb
module PolideportivosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/canchas/index.html.erb
<div class="container">
  <!-- Título principal centrado -->
  <h1 class="title-centered">
    DETALLE DE <%= @polideportivo.nombre %>
  </h1>

  <!-- Botón para ir al inicio -->
  <div class="button-container">
    <%= link_to("HOME", polideportivos_path, class: "button button-primary") %>
  </div>
  <div class="button-container">
    <%= link_to("Agregar cancha", new_polideportivo_cancha_path(@polideportivo), class: "button button-primary") %>
  </div>

  <!-- Sección adicional para la información de contacto y mapa -->
  <div class="info-container">
  <h2>Información de Contacto</h2>
  <p><strong>Nombre:</strong> <%= @polideportivo.nombre %></p>
  <p><strong>Contacto:</strong> <%= @polideportivo.contacto %></p>
  <p><strong>Ubicación:</strong> <%= @polideportivo.ubicacion %></p>
  </div>


<!-- Verificar si hay canchas disponibles -->
<% if @canchas.present? %>
  <div class="card-container">
    <% @canchas.each do |cancha| %>
      <div class="card">
        <h2 class="card-title"><%= cancha.nombre %></h2>

        <!-- Imagen de la cancha -->
        <% if cancha.imagen.attached? %>
          <div class="card-image">
            <%= image_tag cancha.imagen, class: "card-image" %>
          </div>
        <% else %>
          <div class="card-image-placeholder">
            Imagen no disponible
          </div>
        <% end %>

        <!-- Contenido de la tarjeta -->
        <div class="card-content">
          <p class="card-category"><%= cancha.descripcion %></p>
          <p>Precio Día: S/ <%= cancha.precio_dia %></p>
          <p>Precio Noche: S/ <%= cancha.precio_noche %></p>

          <!-- Botones para reservar la cancha y ver reservas -->
          <div class="button-container">
            <%= link_to "Reservar cancha", new_polideportivo_cancha_reserva_path(@polideportivo, cancha), class: "button" %>
            <%= link_to "Ver reservas", polideportivo_cancha_reservas_path(@polideportivo, cancha), class: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No hay canchas disponibles para este polideportivo.</p>
<% end %>

</div>

app/views/canchas/new.html.erb
<%= form_with(model: [@polideportivo, @cancha], local: true, html: { multipart: true }) do |form| %>
  <h1>Crear Nueva Cancha</h1>

  <div class="field">
    <%= form.label :nombre, "Nombre" %>
    <%= form.text_field :nombre, required: true %>
  </div>

  <div class="field">
    <%= form.label :descripcion, "Descripción" %>
    <%= form.text_area :descripcion, required: true %>
  </div>

  <div class="field">
    <%= form.label :precio_dia, "Precio Día (S/)" %>
    <%= form.number_field :precio_dia, step: 0.01, required: true %>
  </div>

  <div class="field">
    <%= form.label :precio_noche, "Precio Noche (S/)" %>
    <%= form.number_field :precio_noche, step: 0.01, required: true %>
  </div>

  <div class="field">
    <%= form.label :tipo, "Tipo de Cancha" %>
    <%= form.select :tipo, Cancha.tipos.keys.map { |k| [k.humanize, k] }, prompt: "Seleccione el tipo de cancha" %>
  </div>

  <div class="field">
    <%= form.label :imagen, "Imagen" %>
    <%= form.file_field :imagen %>
  </div>

  <div class="actions">
    <%= form.submit "Crear Cancha" %>
  </div>
<% end %>

app/views/clientes/create.html.erb
<h1>Clientes#create</h1>
<p>Find me in app/views/clientes/create.html.erb</p>

app/views/clientes/new.html.erb
<h1>Registrar Nuevo Cliente</h1>
<%= form_with(model: @cliente, local: true) do |form| %>
  <div>
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>
  <div>
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.submit "Registrar" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <!-- Encabezado -->
    <header class="header">
      <div class="container">
        <h1 class="header-title">Gu Peloter FU!</h1>
        <nav class="nav">
          <%= link_to "Inicio", root_path, class: "button" %>

          <%= link_to "Polideportivos", polideportivos_path, class: "button" %>
        </nav>
      </div>
    </header>

    <!-- Contenido principal -->
    <main class="main-content">
      <%= yield %>
    </main>

    <!-- Pie de página -->
    <footer class="footer">
      <div class="container">
        <p>&copy; <%= Time.current.year %> Mi Aplicación. Todos los derechos reservados.</p>
        <nav class="footer-nav">
        </nav>
      </div>
    </footer>
  </body>
</html>

app/views/polideportivos/edit.html.erb
<%= form_with(model: @polideportivo, local: true) do |form| %>
    <div class="field">
        <%= form.label :nombre, "Nombre" %>
        <%= form.text_field :nombre %>
    </div>

    <div class="field">
        <%= form.label :contacto, "Contacto" %>
        <%= form.text_field :contacto %>
    </div>

    <div class="field">
        <%= form.label :ubicacion, "Ubicación" %>
        <%= form.text_field :ubicacion %>
    </div>

    <div class="field">
        <%= form.label :ubicacion_api, "API de Ubicación" %>
        <%= form.text_area :ubicacion_api, placeholder: "Inserta tu API de Google Maps aquí" %>
    </div>

    <div class="actions">
        <%= form.submit "Actualizar", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/polideportivos/index.html.erb
<div class="container">
  <h1 class="center-title">LISTA DE POLIDEPORTIVOS</h1>
  <!-- Botón para añadir un nuevo Polideportivo -->
  <div class="button-container">
    <%= link_to "Nuevo Polideportivo", new_polideportivo_path, class: "button" %>
  </div>

  <!-- Contenedor para las tarjetas -->
  <div class="card-container">
    <% @polideportivos.each do |polideportivo| %>
      <div class="card">
        <!-- Imagen del polideportivo -->
        <% if polideportivo.imagen.attached? %>
          <%= image_tag polideportivo.imagen, class: "card-image", alt: "Imagen de #{polideportivo.nombre}" %>
        <% else %>
          <p class="card-image-placeholder">No hay imagen disponible</p>
        <% end %>

        <!-- Contenido de la tarjeta -->
        <div class="card-content">
          <h2 class="card-title"><%= polideportivo.nombre %></h2>

          <!-- Botón para ver el listado de canchas -->
          <div class="button-container">
            <%= link_to "Ver listado de canchas", polideportivo_canchas_path(polideportivo), class: "button button-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/polideportivos/new.html.erb
<div class="centered-card-container">
<div class="centered-card">
  <%= form_with(model: @polideportivo, local: true, html: { multipart: true }) do |form| %>
    <h1>Nuevo Polideportivo</h1>

    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :nombre, required: true %>
    </div>

    <div class="field">
      <%= form.label :ubicacion %>
      <%= form.text_field :ubicacion %>
    </div>

    <div class="field">
      <%= form.label :categoria %>
      <%= form.text_field :categoria %>
    </div>

    <div class="field">
      <%= form.label :descripcion %>
      <%= form.text_area :descripcion %>
    </div>

    <div class="field">
      <%= form.label :contacto %>
      <%= form.text_field :contacto %>
    </div>

    <div class="field">
      <%= form.label :ubicacion_api, "Ubicación API" %>
      <%= form.text_field :ubicacion_api %>
    </div>

    <div class="field">
      <%= form.label :imagen %>
      <%= form.file_field :imagen %>
    </div>

    <div class="actions">
      <%= form.submit "Crear Polideportivo"%>
    </div>
  <% end %>
  </div>
</div>

app/views/reservas/index.html.erb
<div class="centered-card-container">
  <div class="centered-card">
    <h1 class="center-title">Reservas para la Cancha: <%= @cancha.nombre %></h1>
    <h2 class="center-title">Polideportivo: <%= @polideportivo.nombre %></h2>

    <% if @reservas.any? %>
      <table class="table">
        <thead>
          <tr>
            <th>Cliente</th>
            <th>Teléfono</th>
            <th>Email</th>
            <th>Fecha</th>
            <th>Hora Inicio</th>
            <th>Hora Fin</th>
          </tr>
        </thead>
        <tbody>
          <% @reservas.each do |reserva| %>
            <tr>
              <td><%= reserva.cliente.nombre %></td>
              <td><%= reserva.cliente.telefono %></td>
              <td><%= reserva.cliente.email %></td>
              <td><%= reserva.fecha %></td>
              <td><%= reserva.hora_inicio.strftime("%H:%M") %></td>
              <td><%= reserva.hora_fin.strftime("%H:%M") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No hay reservas para esta cancha.</p>
    <% end %>

    <div class="button-container">
      <%= link_to "Volver a Canchas", polideportivo_canchas_path(@polideportivo), class: "button button-secondary" %>
    </div>
  </div>
</div>

app/views/reservas/new.html.erb
<div class="body">

  <%= form_with(model: @reserva, url: polideportivo_cancha_reservas_path(@polideportivo, @cancha), local: true) do |form| %>
    <div class="centered-card-container">
      <div class="centered-card">
          <h1 class="center-title">Crear Nueva Reserva</h1>
          <!-- Información del Cliente -->
          <h2 class="section-title">Información del Cliente</h2>

          <%= form.fields_for :cliente do |cliente_form| %>
            <div class="field">
              <%= cliente_form.label :nombre, class: "field-label" %>
              <%= cliente_form.text_field :nombre, class: "field-input" %>
            </div>

            <div class="field">
              <%= cliente_form.label :telefono, class: "field-label" %>
              <%= cliente_form.text_field :telefono, class: "field-input" %>
            </div>

            <div class="field">
              <%= cliente_form.label :email, class: "field-label" %>
              <%= cliente_form.email_field :email, class: "field-input" %>
            </div>
          <% end %>

          <!-- Información de la Reserva -->
          <h2 class="section-title">Información de la Reserva</h2>

          <div class="field">
            <%= form.label :fecha, class: "field-label" %>
            <%= form.date_field :fecha, class: "field-input" %>
          </div>

          <div class="field">
            <%= form.label :hora_inicio, class: "field-label" %>
            <%= form.time_field :hora_inicio, class: "field-input" %>
          </div>

          <div class="field">
            <%= form.label :hora_fin, class: "field-label" %>
            <%= form.time_field :hora_fin, class: "field-input" %>
          </div>

          <!-- Botón de envío -->
          <div class="actions">
            <%= form.submit "Crear Reserva y Cliente", class: "button button-primary" %>
          </div>
        </div>
    </div>

    <% end %>

</div>